name: Create Server JSON and Update Repo

on:
  issues:
    types: [labeled]

jobs:
  create-json-and-update:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'new-server'
    steps:
      - name: Check if user is authorized
        env:
          SENDER: ${{ github.event.sender.login }}
        run: |
          # Custom list of authorized users (GitHub usernames)
          AUTHORIZED_USERS="jeremy-dai-txyz JoJoJoJoJoJoJo niechen" 
          if echo "$AUTHORIZED_USERS" | grep -q -w "$SENDER"; then
            echo "User $SENDER is authorized"
          else
            echo "User $SENDER is not authorized"
            exit 1  # Fail the workflow if unauthorized
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openai

      - name: Run the script
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          python scripts/get_manifest.py "$ISSUE_BODY"

      - name: Commit the new content
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Update repo with JSON content from issue #${{ github.event.issue.number }}" || echo "No changes to commit"
          git push