on:
  release:
    types:
      - published

name: Release

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
 