name: Semantic Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  semver-check:
    name: Validate Semantic Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
          ci: true
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create comment content
        id: create-comment
        run: |
          if [ "${{ steps.semantic.outputs.new_release_version }}" != "" ]; then
            echo "comment_body=## Semantic Version Check\n\n✅ Valid semantic version changes detected!\n\nNext version will be: **${{ steps.semantic.outputs.new_release_version }}**" >> $GITHUB_OUTPUT
          else
            echo "comment_body=## Semantic Version Check\n\n⚠️ No semantic version changes detected.\n\nPlease ensure your commits follow the [Conventional Commits](https://www.conventionalcommits.org/) format:\n\n- \`feat: new feature\` (triggers MINOR version bump)\n- \`fix: bug fix\` (triggers PATCH version bump)\n- \`BREAKING CHANGE: description\` (triggers MAJOR version bump)" >> $GITHUB_OUTPUT
          fi

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Semantic Version Check'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.create-comment.outputs.comment_body }}
          edit-mode: replace 